USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[CARS]    Script Date: 06/06/2021 15:37:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CARS](
	[ID] [float] NOT NULL,
	[DESCRIPTION] [varchar](50) NULL,
	[PLATE] [varchar](8) NULL,
	[MODEL] [varchar](15) NULL,
 CONSTRAINT [PK_CARS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


