USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[USERS]    Script Date: 06/06/2021 15:40:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USERS](
	[ID] [float] NOT NULL,
	[CODLOJA] [float] NOT NULL,
	[DESCRIPTION] [varchar](50) NOT NULL,
	[ACTIVE] [bit] NOT NULL,
	[OFFICE] [varchar](15) NOT NULL,
	[PASSWORD] [varchar](64) NOT NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


