--ALTER TABLE NVENDA2 ADD STATUS VARCHAR(15) NULL;

CREATE VIEW [dbo].[VIEW_NVENDA2_FULL] (CODIGOVENDA, CODCLIENTE, NOME, VALORPROD, DESCONTO, TOTALVENDA, EMISSAO, STATUS,
ENDERECO, NUMERO, BAIRRO, CIDADE, ESTADO, PONTOREF, OBS, VENDEDOR, FONE, CGC_CPF, INS_RG) AS
SELECT A.CODIGOVENDA, A.CODCLIENTE, B.NOME, A.VALORPROD, A.DESCONTO, A.TOTALVENDA, A.EMISSAO, 
A.STATUS, B.ENDERECO, B.NUMERO_END, B.BAIRRO, B.CIDADE, B.ESTADO, C.PONTOREF, C.OBS, D.NOME, 
B.FONE, B.CGC_CPF, B.INS_RG
FROM NVENDA2 A 
LEFT JOIN CLIENTES B ON A.CODCLIENTE = B.CODIGO
LEFT JOIN PONTO_REFERENCIA C ON A.CODIGOVENDA = C.CODIGOVENDA
LEFT JOIN FUNCIONARIO D ON A.CODVENDEDOR = D.CODIGO
WHERE A.O_V = 2
