--ALTER TABLE NVENDA2 ADD STATUS VARCHAR(15) NULL;


CREATE VIEW [dbo].[VIEW_NVENDA2_FULL] (CODIGOVENDA, CODCLIENTE, NOME, VALORPROD, DESCONTO, TOTALVENDA, EMISSAO, STATUS,
ENDERECO, BAIRRO, CIDADE, ESTADO, PONTOREF, OBS, VENDEDOR) AS
SELECT A.CODIGOVENDA, A.CODCLIENTE, B.NOME, A.VALORPROD, A.DESCONTO, A.TOTALVENDA, A.EMISSAO, 
A.STATUS, B.ENDERECO, B.BAIRRO, B.CIDADE, B.ESTADO, C.PONTOREF, C.OBS, D.NOME
FROM NVENDA2 A 
LEFT JOIN CLIENTES B ON A.CODCLIENTE = B.CODIGO
LEFT JOIN PONTO_REFERENCIA C ON A.CODIGOVENDA = C.CODIGOVENDA
LEFT JOIN FUNCIONARIO D ON A.CODVENDEDOR = D.CODIGO
WHERE A.O_V = 2