USE [SONO_TESTE]
GO

/****** Object:  View [dbo].[VIEW_ORCPARCLOJA]    Script Date: 15/06/2021 18:22:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_ORCPARCLOJA] AS
SELECT A.TITULO, A.PARCELA, A.VENCIMENTO, A.VALOR, B.NOME FORMPAGTO FROM ORCPARC A
INNER JOIN PAGTO B ON A.FORMPAGTO = B.CODIGO

GO


