USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[DELIVERYS_PROD]    Script Date: 08/25/2021 17:15:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DELIVERYS_PROD](
	[ID_DELIVERY] [float] NOT NULL,
	[ID_SALE] [float] NOT NULL,
	[CODLOJA] [float] NOT NULL,
	[COD_ORIGINAL] [varchar](20) NOT NULL,
	[D_MOUNTING] [date] NULL,
	[D_DELIVERING] [date] NULL,
	[D_DELIVERED] [date] NULL,
	[DELIVERED] [bit] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


