USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[ORCPARC]    Script Date: 06/08/2021 09:54:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORCPARC](
	[ID_SALES] [float] NOT NULL,
	[CODLOJA] [float] NOT NULL,
	[PARCELA] [float] NOT NULL,
	[VENCIMENTO] [datetime] NOT NULL,
	[VALOR] [float] NOT NULL,
	[FORMPAGTO] [varchar](30) NOT NULL,
 CONSTRAINT [PK_ORCPARC] PRIMARY KEY CLUSTERED 
(
	[ID_SALES] ASC,
	[CODLOJA] ASC,
	[PARCELA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


