USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[SALES_PROD]    Script Date: 06/06/2021 15:40:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SALES_PROD](
	[ID_SALES] [float] NOT NULL,
	[CODLOJA] [float] NOT NULL,
	[CODPRODUTO] [float] NOT NULL,
	[COD_ORIGINAL] [varchar](20) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
	[DESCRICAO] [varchar](50) NOT NULL,
	[QUANTIDADE] [float] NOT NULL,
	[UNITARIO1] [float] NOT NULL,
	[DESCONTO] [float] NOT NULL,
	[NVTOTAL] [float] NOT NULL,
 CONSTRAINT [PK_SALES_PROD] PRIMARY KEY CLUSTERED 
(
	[CODPRODUTO] ASC,
	[ID_SALES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


