USE [SONO]
GO

/****** Object:  View [dbo].[VIEW_KARDEX_PRODUTOS]    Script Date: 19/08/2021 11:45:56 ******/
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO


ALTER VIEW [dbo].[VIEW_KARDEX_PRODUTOS](
 LOJA,
 DATA,
 HORA,
 MODULO,
 DOCUMENTO,
 CODPRODUTO,
 QUANT_ENTRADA,
 QUANT_SAIDA,
 ENTRADA_SAIDA,
 OBS,
 CODCF,
 NOMECF,
 EMBALAGEM,
 CALCULAR,
 VALORUNITARIO,
 LOTE,
 TIPOCLI_FOR_FUN,
 USUARIO,
 ITEM,
 MU_ITEM,
 MU_QTE_MENORUN,
 MU_UNIDADE
 )
  AS
SELECT     N.CODLOJA AS LOJA, N.DATA_CHEGADA AS DATA, N.HORA_LANCAMENTO AS HORA, CONVERT(VARCHAR(30), 'NF ENTRADA') AS MODULO, CONVERT(CHAR(15), 
                      N.NUM_DOC) AS DOCUMENTO, I.PRODUTO AS CODPRODUTO, 
                      CASE 
                         WHEN (I.QUANTIDADE_PROCESSADA > 0) THEN I.QUANTIDADE_PROCESSADA 
                      ELSE 
                      CASE WHEN (I.MU_ITEM > 0) THEN I.QUANTIDADE ELSE (I.QUANTIDADE * ISNULL(I.EMBALAGEM, 1)) END END AS QUANT_ENTRADA, 
                      0 AS QUANT_SAIDA, 'E' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 'Compra NF: ' + N.NUM_DOC) AS OBS, N.CODFOR AS CODCF, 
                      F.NOME AS NOMECF, I.EMBALAGEM, 'S' AS CALCULAR, I.UNITARIO AS VALORUNITARIO, CONVERT(VARCHAR(30), L.LOTE) AS LOTE, CONVERT(VARCHAR(30), 
                      'Fornecedor') AS TIPOCLI_FOR_FUN, USU.NOME AS USUARIO, I.ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         NFITENS AS I WITH (NOLOCK) INNER JOIN
                      NFISCAL AS N WITH (NOLOCK) ON I.NNF = N.NF LEFT OUTER JOIN
                      CADFOR AS F ON N.CODFOR = F.CODIGO LEFT OUTER JOIN
                      USUARIONEW AS USU ON N.CODUSUARIO = USU.CODIGO LEFT OUTER JOIN
                      LOTES_PROD_COMPRAS AS L ON N.NF = L.NF AND I.PRODUTO = L.CODPRODUTO AND N.CODLOJA = L.CODLOJA
WHERE     (N.PROCESS = 'T') AND (N.PARTICIPA_ESTOQUE = 'S')
 AND (I.NNF NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = I.NNF) AND (K.CODLOJA = I.CODLOJA) AND (K.PROCESSAR = 'S')))
AND (I.PRODUTO NOT IN 
                          (SELECT CODIGOPRODUTOORIGEM 
                            FROM RATEIO_ITENS AS RI WITH(NOLOCK)
                            WHERE (RI.NNF = I.NNF) AND (RI.CODIGOLOJA = I.CODLOJA)))                                           
UNION
SELECT     N.CODLOJA AS LOJA, N.EMISSAO AS DATA, N.HORA, CONVERT(VARCHAR(30), 'VENDA') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, N.CODIGOVENDA)) 
                      AS DOCUMENTO, I.CODPRODUTO, 0 AS QUANT_ENTRADA, I.QUANTIDADE AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 
                      'Vnd cupom: ' + N.CUPOM) AS OBS, N.CODCLIENTE AS CODCF, N.NOMECLI AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.UNITARIO2 AS VALORUNITARIO, 
                      CONVERT(VARCHAR(30), L.LOTE) AS LOTE, CONVERT(VARCHAR(30), 'Cliente') AS TIPOCLI_FOR_FUN, N.NOMEUSUARIO AS USUARIO, I.ITEM, I.MU_ITEM, 
                      I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         NVENDI2 AS I WITH (NOLOCK) INNER JOIN
                      NVENDA2 AS N WITH (NOLOCK) ON I.NUMVENDA = N.CODIGOVENDA AND I.CODPRODUTO NOT IN
                          (SELECT     CODPRODUTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(30), CONVERT(NUMERIC,I.NUMVENDA))) AND (K.CODLOJA = N.CODLOJA) AND (K.PROCESSAR = 'S')) LEFT OUTER JOIN
                          (SELECT     CODIGOVENDA, CODPRODUTO, MAX(LOTE) AS LOTE
                            FROM          LOTES_PROD_VBALCAO AS LL
                            GROUP BY CODIGOVENDA, CODPRODUTO) AS L ON N.CODIGOVENDA = L.CODIGOVENDA AND I.CODPRODUTO = L.CODPRODUTO
WHERE     (N.O_V = '2') AND ((I.ITEM_PROJETO <> '1') OR (I.ITEM_PROJETO IS NULL)) 
UNION
SELECT     T.CODLOJA AS LOJA, T.EMISSAO AS DATA, T.HORA, CONVERT(VARCHAR(30), 'DEPOSITO LOJA') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      T.CODIGOTRANS)) AS DOCUMENTO, I.CODPRODUTO, 0 AS QUANT_ENTRADA, I.QUANTIDADE AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 
                      'NAO CALC SALDO - ' + T.OBSERVA) AS OBS, 0 AS CODCF, T.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'N' AS CALCULAR, 0 AS VALORUNITARIO, 
                      CONVERT(VARCHAR(30), '') AS LOTE, CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, T.USUARIO, 1 AS ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, 
                      I.MU_UNIDADE
FROM         TRANSPIT AS I WITH (NOLOCK) INNER JOIN
                      TRANSPRO AS T WITH (NOLOCK) ON I.NUMTRANS = T.CODIGOTRANS
UNION
--22/12/2020- Irﬂ buscar somente se n“o existir na tabela KARDEX_PRODUTOS_HISTORICO. ACERTOESTITEM
SELECT     A.CODLOJA AS LOJA, A.EMISSAO AS DATA, A.HORA, CONVERT(VARCHAR(30), 'ACERTO EST SAI LOJA') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      I.CODIGOACERTO)) AS DOCUMENTO, I.CODPRODUTO, 0 AS QUANT_ENTRADA, I.QT_LOJA_ACER AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 
                      A.OBSERV) AS OBS, 0 AS CODCF, A.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, 0 AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, A.USUARIO, 1 AS ITEM, I.MU_ITEM, I.MU_QT_LOJA_ACER AS MU_QTE_MENORUN, 
                      CASE WHEN (I.MU_ITEM > 0) THEN
                          (SELECT     UNIDADE
                            FROM          PRODEXPL_CADASTRO
                            WHERE      CODIGOPRODUTO = I.CODPRODUTO AND ITEM =
                                                       (SELECT     MAX(ITEM)
                                                         FROM          PRODEXPL_CADASTRO
                                                         WHERE      CODIGOPRODUTO = I.CODPRODUTO)) ELSE I.MU_UNIDADE END AS MU_UNIDADE
FROM         ACERTOESTITEM AS I WITH (NOLOCK) INNER JOIN
                      ACERTOESTOQUE AS A WITH (NOLOCK) ON I.CODIGOACERTO = A.CODIGO
WHERE     (I.QT_LOJA_ACER <> 0) AND (I.TIPO_LOJA = 1)
AND (CONVERT(VARCHAR(15),I.CODIGOACERTO) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(15),I.CODIGOACERTO)) AND (K.PROCESSAR = 'S')))

UNION
--22/12/2020- Irﬂ buscar somente se n“o existir na tabela KARDEX_PRODUTOS_HISTORICO. ACERTOESTITEM
SELECT     A.CODLOJA AS LOJA, A.EMISSAO AS DATA, A.HORA, CONVERT(VARCHAR(30), 'ACERTO EST ENT LOJA') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      I.CODIGOACERTO)) AS DOCUMENTO, I.CODPRODUTO, I.QT_LOJA_ACER AS QUANT_ENTRADA, 0 AS QUANT_SAIDA, 'E' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 
                      A.OBSERV) AS OBS, 0 AS CODCF, A.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, 0 AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, A.USUARIO, 1 AS ITEM, I.MU_ITEM, I.MU_QT_LOJA_ACER AS MU_QTE_MENORUN, 
                      CASE WHEN (I.MU_ITEM > 0) THEN
                          (SELECT     UNIDADE
                            FROM          PRODEXPL_CADASTRO
                            WHERE      CODIGOPRODUTO = I.CODPRODUTO AND ITEM =
                                                       (SELECT     MAX(ITEM)
                                                         FROM          PRODEXPL_CADASTRO
                                                         WHERE      CODIGOPRODUTO = I.CODPRODUTO)) ELSE I.MU_UNIDADE END AS MU_UNIDADE
FROM         ACERTOESTITEM AS I WITH (NOLOCK) INNER JOIN
                      ACERTOESTOQUE AS A WITH (NOLOCK) ON I.CODIGOACERTO = A.CODIGO
WHERE     (I.QT_LOJA_ACER <> 0) AND (I.TIPO_LOJA = 0)
AND (CONVERT(VARCHAR(15),I.CODIGOACERTO) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(15),I.CODIGOACERTO)) AND (K.PROCESSAR = 'S')))
UNION
--22/12/2020- Irﬂ buscar somente se n“o existir na tabela KARDEX_PRODUTOS_HISTORICO. ACERTOESTITEM
SELECT     A.CODLOJA AS LOJA, A.EMISSAO AS DATA, A.HORA, CONVERT(VARCHAR(30), 'ACERTO EST SAI DEPO') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      I.CODIGOACERTO)) AS DOCUMENTO, I.CODPRODUTO, 0 AS QUANT_ENTRADA, I.QT_DEPO_ACER AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 
                      A.OBSERV) AS OBS, 0 AS CODCF, A.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, 0 AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, A.USUARIO, 1 AS ITEM, I.MU_ITEM, I.MU_QT_DEPO_ACER AS MU_QTE_MENORUN, 
                      CASE WHEN (I.MU_ITEM > 0) THEN
                          (SELECT     UNIDADE
                            FROM          PRODEXPL_CADASTRO
                            WHERE      CODIGOPRODUTO = I.CODPRODUTO AND ITEM =
                                                       (SELECT     MAX(ITEM)
                                                         FROM          PRODEXPL_CADASTRO
                                                         WHERE      CODIGOPRODUTO = I.CODPRODUTO)) ELSE I.MU_UNIDADE END AS MU_UNIDADE
FROM         ACERTOESTITEM AS I WITH (NOLOCK) INNER JOIN
                      ACERTOESTOQUE AS A WITH (NOLOCK) ON I.CODIGOACERTO = A.CODIGO
WHERE     (I.QT_DEPO_ACER <> 0) AND (I.TIPO_DEPO = 1)
AND (CONVERT(VARCHAR(15),I.CODIGOACERTO) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(15),I.CODIGOACERTO)) AND (K.PROCESSAR = 'S')))
UNION
--22/12/2020- Irﬂ buscar somente se n“o existir na tabela KARDEX_PRODUTOS_HISTORICO. ACERTOESTITEM
SELECT     A.CODLOJA AS LOJA, A.EMISSAO AS DATA, A.HORA, CONVERT(VARCHAR(30), 'ACERTO EST ENT DEPO') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      I.CODIGOACERTO)) AS DOCUMENTO, I.CODPRODUTO, I.QT_DEPO_ACER AS QUANT_ENTRADA, 0 AS QUANT_SAIDA, 'E' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 
                      A.OBSERV) AS OBS, 0 AS CODCF, A.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, 0 AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, A.USUARIO, 1 AS ITEM, I.MU_ITEM, I.MU_QT_DEPO_ACER AS MU_QTE_MENORUN, 
                      CASE WHEN (I.MU_ITEM > 0) THEN
                          (SELECT     UNIDADE
                            FROM          PRODEXPL_CADASTRO
                            WHERE      CODIGOPRODUTO = I.CODPRODUTO AND ITEM =
                                                       (SELECT     MAX(ITEM)
                                                         FROM          PRODEXPL_CADASTRO
                                                         WHERE      CODIGOPRODUTO = I.CODPRODUTO)) ELSE I.MU_UNIDADE END AS MU_UNIDADE
FROM         ACERTOESTITEM AS I WITH (NOLOCK) INNER JOIN
                      ACERTOESTOQUE AS A WITH (NOLOCK) ON I.CODIGOACERTO = A.CODIGO
WHERE     (I.QT_DEPO_ACER <> 0) AND (I.TIPO_DEPO = 0)
AND (CONVERT(VARCHAR(15),I.CODIGOACERTO) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(15),I.CODIGOACERTO)) AND (K.PROCESSAR = 'S')))
UNION
SELECT     O.CODLOJA AS LOJA, O.DTPAGAMENTO AS DATA, O.HORA_LAN AS HORA, CONVERT(VARCHAR(30), 'ORDEM SERVICO') AS MODULO, CONVERT(VARCHAR(15), 
                      CONVERT(numeric, I.CODIGO)) AS DOCUMENTO, I.CODPRODUTO, 0 AS QUANT_ENTRADA, I.QUANTIDADE AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, 
                      CONVERT(VARCHAR(80), 'Ordem Servi™o: ' + CONVERT(VARCHAR(15), CONVERT(numeric, I.CODIGO))) AS OBS, O.CODCLIENTE AS CODCF, 
                      O.NOMECLIENTE AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.VALUNITARIO AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Cliente') AS TIPOCLI_FOR_FUN, I.USUARIO, I.ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         ORDEMITEMPC AS I WITH (NOLOCK) INNER JOIN
                      ORDEMSERV AS O WITH (NOLOCK) ON I.CODIGO = O.CODIGO
WHERE     (I.BAIXADOEST = 2)
UNION
--22/12/2020- Irﬂ buscar somente se n“o existir na tabela KARDEX_PRODUTOS_HISTORICO.
SELECT     T.LOJADESTINO AS LOJA, T.EMISSAO AS DATA, T.HORA, CONVERT(VARCHAR(30), 'TRANSF LOJA ENT') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      T.CODIGO)) AS DOCUMENTO, I.CODPRODUTO, I.QUANTIDADE AS QUANT_ENTRADA, 0 AS QUANT_SAIDA, 'E' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), T.MOTIVO) 
                      AS OBS, 0 AS CODCF, T.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.UNITARIOLIQUIDO AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, T.USUARIO, I.ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         TRANSPRODLOJA AS T WITH (NOLOCK) INNER JOIN
                      TRANSPRODLOJAI AS I WITH (NOLOCK) ON T.CODIGO = I.REGISTRO
WHERE (CONVERT(VARCHAR(30),T.CODIGO) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(30),T.CODIGO)) AND (K.CODLOJA = T.CODLOJA) AND (K.PROCESSAR = 'S')))                       
UNION
--22/12/2020- Irﬂ buscar somente se n“o existir na tabela KARDEX_PRODUTOS_HISTORICO.
SELECT     T.LOJAORIGEM AS LOJA, T.EMISSAO AS DATA, T.HORA, CONVERT(VARCHAR(30), 'TRANSF LOJA SAI') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      T.CODIGO)) AS DOCUMENTO, I.CODPRODUTO, 0 AS QUANT_ENTRADA, I.QUANTIDADE AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), T.MOTIVO) 
                      AS OBS, 0 AS CODCF, T.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.UNITARIOLIQUIDO AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, T.USUARIO, I.ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         TRANSPRODLOJA AS T WITH (NOLOCK) INNER JOIN
                      TRANSPRODLOJAI AS I WITH (NOLOCK) ON T.CODIGO = I.REGISTRO
WHERE (CONVERT(VARCHAR(30),T.CODIGO) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(30),T.CODIGO)) AND (K.CODLOJA = T.CODLOJA) AND (K.PROCESSAR = 'S')))                    
                      
UNION
SELECT     T.CODLOJA AS LOJA, T.EMISSAO AS DATA, T.HORA, CONVERT(VARCHAR(30), 'TRANSF PRO PRO ENT') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      T.CODIGO)) AS DOCUMENTO, T.PRODDESTINO AS CODPRODUTO, T.QTDEDESTINO AS QUANT_ENTRADA, 0 AS QUANT_SAIDA, 'E' AS ENTRADA_SAIDA, 
                      CONVERT(VARCHAR(80), 'Entre produtos') AS OBS, 0 AS CODCF, T.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, 0 AS VALORUNITARIO, 
                      CONVERT(VARCHAR(30), '') AS LOTE, CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, T.USUARIO, 1 AS ITEM, T.MU_ITEM_DESTINO AS MU_ITEM, 
                      T.MU_QTE_MUN_DESTINO AS MU_QTE_MENORUN, T.MU_UNIDADE_DESTINO AS MU_UNIDADE
FROM         TRANSPROPRO AS T WITH (NOLOCK) INNER JOIN
                      PRODUTOS AS P WITH (NOLOCK) ON T.PRODDESTINO = P.CODIGO
UNION
SELECT     T.CODLOJA AS LOJA, T.EMISSAO AS DATA, T.HORA, CONVERT(VARCHAR(30), 'TRANSF PRO PRO SAI') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      T.CODIGO)) AS DOCUMENTO, T.PRODORIGEM AS CODPRODUTO, 0 AS QUANT_ENTRADA, T.QTDEORIGEM AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, 
                      CONVERT(VARCHAR(80), 'Entre produtos') AS OBS, 0 AS CODCF, T.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, 0 AS VALORUNITARIO, 
                      CONVERT(VARCHAR(30), '') AS LOTE, CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, T.USUARIO, 1 AS ITEM, T.MU_ITEM_ORIGEM AS MU_ITEM, 
                      T.MU_QTE_MUN_ORIGEM AS MU_QTE_MENORUN, T.MU_UNIDADE_ORIGEM AS MU_UNIDADE
FROM         TRANSPROPRO AS T WITH (NOLOCK) INNER JOIN
                      PRODUTOS AS P WITH (NOLOCK) ON T.PRODORIGEM = P.CODIGO
UNION
SELECT    N.CODLOJA AS LOJA, N.NC_EMIS AS DATA, N.HORA_LAN AS HORA, CONVERT(VARCHAR(30), 'SAIDA NF DEV FORN') AS MODULO, CONVERT(VARCHAR(15), 
                      CONVERT(numeric, N.NC_NUME)) AS DOCUMENTO, I.NC_PEC AS CODPRODUTO, 0 AS QUANT_ENTRADA, 
                      (I.NQTE * ISNULL(I.EMBALAGEM, 1)) AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, 
                      CONVERT(VARCHAR(80), N.NC_OBS1) AS OBS, N.NC_FORN AS CODCF, F.NOME AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.NVLUN2 AS VALORUNITARIO, 
                      CONVERT(VARCHAR(30), '') AS LOTE, CONVERT(VARCHAR(30), 'Fornecedor') AS TIPOCLI_FOR_FUN, N.NOMEUSU AS USUARIO, I.ITEM, I.MU_ITEM, 
                      I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         NFDEVOLUCAI AS I WITH (NOLOCK) INNER JOIN
                      NFDEVOLUCAO AS N WITH (NOLOCK) ON I.NNF = N.NC_NUME INNER JOIN
                      CADFOR AS F ON N.NC_FORN = F.CODIGO                      
WHERE     (N.BXESTOQUE = 'S') AND (CONVERT(VARCHAR(30), CONVERT(NUMERIC, N.NC_NUME)) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (N.CODLOJA = CODLOJA) AND PROCESSAR = 'S'))
AND (I.NC_PEC NOT IN
                          (SELECT CODIGOPRODUTOORIGEM 
                            FROM VIEW_RATEIO_DEVOLUCAO_FORNECEDOR AS RI WITH(NOLOCK)
                            WHERE (RI.NUMERO_NF = N.NUMERO_NF) AND (RI.CODIGOLOJA = I.CODLOJA)))                             
UNION
SELECT     N.CODLOJA AS LOJA, N.NC_EMIS AS DATA, N.HORA_LAN AS HORA, CONVERT(VARCHAR(30), 'SAIDA NF VDA CONS') AS MODULO, CONVERT(VARCHAR(15), 
                      CONVERT(numeric, N.NC_NUME)) AS DOCUMENTO, I.NC_PEC AS CODPRODUTO, 0 AS QUANT_ENTRADA, I.NQTE AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, 
                      CONVERT(VARCHAR(80), N.NC_OBS1) AS OBS, N.NC_CLIE AS CODCF, N.NC_NOME AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.NVLUN2 AS VALORUNITARIO, 
                      CONVERT(VARCHAR(30), '') AS LOTE, CONVERT(VARCHAR(30), 'Cliente') AS TIPOCLI_FOR_FUN, U.NOME AS USUARIO, I.ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, 
                      I.MU_UNIDADE
FROM         NFVENDI AS I WITH (NOLOCK) INNER JOIN
                      NFVENDA AS N WITH (NOLOCK) ON I.NNF = N.NC_NUME LEFT OUTER JOIN
                      USUARIONEW AS U WITH (NOLOCK) ON U.CODIGO = N.CODUSUARIO
WHERE     (N.BAIXAESTOQUE = 'S') AND (CONVERT(VARCHAR(30), CONVERT(NUMERIC, N.NC_NUME)) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (N.CODLOJA = CODLOJA) AND PROCESSAR = 'S'))
UNION
--22/12/2020- Irﬂ buscar somente se n“o existir na tabela KARDEX_PRODUTOS_HISTORICO.
SELECT     T.CODLOJA AS LOJA, T.EMISSAO AS DATA, T.HORA, CONVERT(VARCHAR(30), 'TRANS ENT_SAI SAI') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, 
                      T.CODIGO)) AS DOCUMENTO, I.CODPRODUTO, 0 AS QUANT_ENTRADA, I.QUANTIDADE AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), T.MOTIVO) 
                      AS OBS, 0 AS CODCF, T.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.PRECO_COMPRA AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, T.USUARIO, I.ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         TRANS_ENT_SAI AS T WITH (NOLOCK) INNER JOIN
                      TRANS_ENT_SAII AS I WITH (NOLOCK) ON T.CODIGO = I.REGISTRO
WHERE     (T.TIPODC = 'D')
AND (CONVERT(VARCHAR(15),T.CODIGO) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(15),T.CODIGO)) AND (K.CODLOJA = T.CODLOJA) AND (K.PROCESSAR = 'S')))

UNION
--22/12/2020- Irﬂ buscar somente se n“o existir na tabela KARDEX_PRODUTOS_HISTORICO.
SELECT     T.CODLOJA AS LOJA, T.EMISSAO AS DATA, T.HORA, CONVERT(VARCHAR(30), 'TRANS ENT_SAI ENT') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, T.CODIGO)) AS DOCUMENTO, I.CODPRODUTO, I.QUANTIDADE AS QUANT_ENTRADA, 0 AS QUANT_SAIDA, 'E' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), T.MOTIVO) 
                      AS OBS, 0 AS CODCF, T.USUARIO AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.PRECO_COMPRA AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, 
                      CONVERT(VARCHAR(30), 'Funcionªrio') AS TIPOCLI_FOR_FUN, T.USUARIO, I.ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         TRANS_ENT_SAI AS T WITH (NOLOCK) INNER JOIN
                      TRANS_ENT_SAII AS I WITH (NOLOCK) ON T.CODIGO = I.REGISTRO
WHERE     (T.TIPODC = 'C')
AND (CONVERT(VARCHAR(15),T.CODIGO) NOT IN
                          (SELECT     DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK)
                            WHERE      (K.DOCUMENTO = CONVERT(VARCHAR(15),T.CODIGO)) AND (K.CODLOJA = T.CODLOJA) AND (K.PROCESSAR = 'S')))
                            
UNION
SELECT     N.CODLOJA AS LOJA, N.EMISSAO AS DATA, N.HORA, CONVERT(VARCHAR(30), 'PERDAS') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, N.CODIGO)) 
                      AS DOCUMENTO, I.CODPRODUTO, 0 AS QUANT_ENTRADA, I.QUANTIDADE AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), N.OBSERVA) AS OBS, 
                      0 AS CODCF, F.NOME AS NOMECF, 0 AS EMBALAGEM, 'S' AS CALCULAR, I.VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, CONVERT(VARCHAR(30), 
                      'Funcionªrio') AS TIPOCLI_FOR_FUN, N.USUARIO, I.ITEM, I.MU_ITEM, I.MU_QTE_MENORUN, I.MU_UNIDADE
FROM         PERDAS_PRODUTOSI AS I WITH (NOLOCK) INNER JOIN
                      PERDAS_PRODUTOS AS N ON I.CODIGO_PERDAS = N.CODIGO LEFT OUTER JOIN
                      FUNCIONARIO AS F ON N.CODRESP = F.CODIGO
WHERE N.CANCELADA='N' AND N.CODIGO NOT IN (SELECT DOCUMENTO FROM KARDEX_PRODUTOS_HISTORICO AS K WITH (NOLOCK) WHERE      
                                          (K.DOCUMENTO = N.CODIGO) AND (K.CODLOJA = N.CODLOJA) AND (K.PROCESSAR = 'S') AND (K.MODULO='PERDAS'))
UNION
SELECT   L2.CODLOJA AS LOJA, L.DATA, L2.HORA, CONVERT(VARCHAR(30), 'VENDA') AS MODULO, CONVERT(VARCHAR(15), CONVERT(numeric, L.NUMVENDA)) 
                      AS DOCUMENTO, L.CODPRODUTO, 0 AS QUANT_ENTRADA, L.QUANTIDADE AS QUANT_SAIDA, 'S' AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 
                      'Cod. Vnd ' + CONVERT(VARCHAR(15), CONVERT(varchar(15), CONVERT(numeric, L.NUMVENDA)))) AS OBS, L2.CODCLIENTE, L2.NOMECLI, 0 AS EMBALAGEM, 
                      'S' AS CALCULAR, L.UNITARIO1 AS VALORUNITARIO, CONVERT(VARCHAR(30), '') AS LOTE, CONVERT(VARCHAR(30), 'Cliente') AS TIPOCLI_FOR_FUN, 
                      L2.NOMEUSUARIO AS USUARIO, 1 ITEM, L.MU_ITEM, L.MU_QTE_MENORUN, L.MU_UNIDADE
FROM         LOG_NVENDI2 AS L WITH (NOLOCK) INNER JOIN
                      LOG_NVENDA2 AS L2 WITH (NOLOCK) ON L.IDENTIFICADOR = L2.IDENTIFICADOR                    
WHERE     (CONVERT(VARCHAR(30), CONVERT(NUMERIC ,L.NUMVENDA)) NOT IN
                          (SELECT    DOCUMENTO
                            FROM          KARDEX_PRODUTOS_HISTORICO K WITH (NOLOCK)
                            WHERE      (L2.CODLOJA = K.CODLOJA) AND (L.CODPRODUTO = K.CODPRODUTO) AND (K.PROCESSAR = 'S'))  AND (L2.O_V = '2') AND (L.DATADEV IS NULL) AND (L.NCOMPOSTO IS NULL)) AND (L.ITEM_PROJETO <> '1' OR L.ITEM_PROJETO IS NULL)
GROUP BY  L2.CODLOJA, L.DATA, L2.HORA, L.NUMVENDA, L.QUANTIDADE, 
                      L.CODPRODUTO, L2.CODCLIENTE, L2.NOMECLI, 
                      L.UNITARIO1, L.MU_ITEM, L.MU_QTE_MENORUN, L.MU_UNIDADE,L2.NOMEUSUARIO                    
UNION
SELECT     CODLOJA AS LOJA, DATA, HORA, MODULO, DOCUMENTO, CODPRODUTO, QUANT_ENTRADA, QUANT_SAIDA, ENTRADA_SAIDA, OBS, CODCF, NOMECF, ISNULL(EMBALAGEM, 1), 
                      CALCULAR, VALORUNITARIO, LOTE, CONVERT(VARCHAR(30), 'Cliente') AS TIPOCLI_FOR_FUN, USUARIO, ITEM, MU_ITEM, MU_QTD_MENORUN, MU_UNIDADE
FROM         KARDEX_PRODUTOS_HISTORICO WITH (NOLOCK)
WHERE PROCESSAR = 'S'
UNION
SELECT 1 AS LOJA, C.D_ENTREGA2 AS DATA, CONVERT(VARCHAR(8), '00:00:00') AS HORA, CONVERT(VARCHAR(30), 'ENTREGA') AS MODULO, 
CONVERT(VARCHAR(15), CONVERT(numeric, C.ID_SALES)) AS DOCUMENTO, A.CODIGO AS CODPRODUTO, 
0 AS QUANT_ENTRADA, C.QTD AS QUANT_SAIDA, CONVERT(CHAR(1), 'S') AS ENTRADA_SAIDA, CONVERT(VARCHAR(80), 'Modulo de entregas') AS OBS, 
C.ID_CLIENT AS CODCF, C.NOMECLI AS NOMECF, 1 AS EMBALAGEM, CONVERT(VARCHAR(1), 'S') AS CALCULAR, C.UNITARIO1 AS VALORUNITARIO, 
CONVERT(VARCHAR(30), NULL) AS LOTE, CONVERT(VARCHAR(30), 'Cliente') AS TIPOCLI_FOR_FUN,
CONVERT(VARCHAR(30), 'Padrao') AS USUARIO, 1 AS ITEM, -1 AS MU_ITEM, 1 AS MU_QTE_MENORUN, CONVERT(CHAR(3), 'UN') MU_UNIDADE
	FROM PRODUTOS A
	INNER JOIN (SELECT A.COD_ORIGINAL, SUM(A.QUANTIDADE) QTD, B.D_ENTREGA2, B.ID_SALES, B.NOMECLI, B.ID_CLIENT, A.UNITARIO1
				FROM SONOENTREGAS..SALES_PROD A
				INNER JOIN SONOENTREGAS..SALES B ON A.ID_SALES = B.ID_SALES
				GROUP BY A.COD_ORIGINAL, B.D_ENTREGA2, B.ID_SALES, A.CODPRODUTO, B.NOMECLI, B.ID_CLIENT, A.UNITARIO1) C 
	ON C.COD_ORIGINAL = A.ALTERNATI
				


GO


