CREATE VIEW [dbo].[View_Deliv_Sales]
AS
SELECT dbo.DELIVERYS_SALES.ID_DELIVERY, dbo.SALES.ID_SALES, dbo.SALES.CODLOJA, dbo.SALES.ID_CLIENT, 
dbo.SALES.NOMECLI, dbo.SALES.TOTAL_PROD, dbo.SALES.DESCONTO, dbo.SALES.TOTAL, dbo.SALES.EMISSAO, 
dbo.SALES.STATUS, dbo.SALES.ENDERECO, dbo.SALES.NUMERO, dbo.SALES.BAIRRO, dbo.SALES.CIDADE, 
dbo.SALES.ESTADO, dbo.SALES.PONTOREF, dbo.SALES.OBS, dbo.SALES.VENDEDOR, dbo.SALES.FONE, 
dbo.SALES.CGC_CPF,dbo.SALES.INS_RG, dbo.SALES.FAX
FROM dbo.DELIVERYS_SALES 
INNER JOIN dbo.SALES ON dbo.DELIVERYS_SALES.ID_SALE = dbo.SALES.ID_SALES 
AND dbo.SALES.CODLOJA = dbo.DELIVERYS_SALES.CODLOJA

GO