USE [SONO_TESTE]
GO

/****** Object:  View [dbo].[VIEW_NVENDI2]    Script Date: 04/03/2022 07:16:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VIEW_NVENDI2]
AS
SELECT A.NUMVENDA, A.CODPRODUTO, B.ALTERNATI, A.DESCRICAO, A.QUANTIDADE, A.UNITARIO1, A.NPDESC, A.STATUS,
A.NVTOTAL 
FROM NVENDI2 A
INNER JOIN PRODUTOS B ON A.CODPRODUTO = B.CODIGO

GO


