--ALTER TABLE NVENDÍ2 ADD STATUS VARCHAR(15) NULL;

CREATE VIEW VIEW_NVENDI2 (NUMVENDA, CODPRODUTO, COD_ORIGINAL, DESCRICAO, QUANTIDADE, UNITARIO1,
DESCONTO, NVTOTAL) AS
SELECT A.NUMVENDA, A.CODPRODUTO, B.ALTERNATI, A.DESCRICAO, A.QUANTIDADE, A.UNITARIO1, A.NPDESC,
A.NVTOTAL 
FROM NVENDI2 A
INNER JOIN PRODUTOS B ON A.CODPRODUTO = B.CODIGO