USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[DELIVERYS_PROD]    Script Date: 12/21/2021 11:55:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DELIVERYS_PROD](
	[ID_DELIVERY] [float] NOT NULL,
	[ID_SALE] [float] NOT NULL,
	[CODLOJA] [float] NOT NULL,
	[QTD_DELIV] [float] NOT NULL,
	[COD_ORIGINAL] [varchar](20) NOT NULL,
	[D_MOUNTING] [datetime] NULL,
	[D_DELIVERING] [datetime] NULL,
	[D_DELIVERED] [datetime] NULL,
	[DELIVERED] [bit] NOT NULL,
	[REASON_RETURN] [varchar](250) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


