CREATE TABLE FORECAST(
	id int IDENTITY(1,1) PRIMARY KEY,
	[date] date NOT NULL UNIQUE,
	[status] bit,
	idUserCreated float NOT NULL FOREIGN KEY REFERENCES USERS(ID),
	idUserFinished float NULL FOREIGN KEY REFERENCES USERS(ID),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
