USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[LOJAS]    Script Date: 05/20/2022 07:44:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LOJAS](
	[CODLOJA] [float] NULL,
	[DESCRICAO] [varchar](50) NULL,
	[DESC_ABREV] [varchar](10) NOT NULL,
	[FULL_NAME] [varchar](40) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[LOJAS] ADD  CONSTRAINT [DF__LOJAS__DESC_ABRE__6F1576F7]  DEFAULT ('DEF') FOR [DESC_ABREV]
GO

ALTER TABLE [dbo].[LOJAS] ADD  DEFAULT ('A') FOR [FULL_NAME]
GO