USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[MAINTENANCE_DELIV]    Script Date: 05/20/2022 07:27:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MAINTENANCE_DELIV](
	[ID] [float] NOT NULL,
	[ID_MAINT] [float] NOT NULL,
	[D_MOUNTING] [datetime] NOT NULL,
	[D_DELIVING] [datetime] NULL,
	[D_DELIVERED] [datetime] NULL,
	[DONE] [bit] NOT NULL,
	[REASON_RETURN] [varchar](250) NULL,
	[ID_DRIVER] [float] NOT NULL,
	[ID_ASSISTANT] [float] NOT NULL,
	[ID_DELIV_MAIN] [float] NULL,
	[ID_USER] [float] NOT NULL,
	[OBS] [varchar](255) NULL,
 CONSTRAINT [PK_MAINTENANCE_DELIV] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MAINTENANCE_DELIV] ADD  DEFAULT ((1)) FOR [ID_USER]
GO


