USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[MAINTENANCE_VISIT]    Script Date: 05/20/2022 07:27:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MAINTENANCE_VISIT](
	[ID_MAIN] [float] NOT NULL,
	[DATE_PREV] [date] NOT NULL,
	[HOURS_PREV] [varchar](5) NOT NULL,
	[DATE] [date] NULL,
	[OBS] [varchar](250) NULL,
	[TO_CD] [bit] NULL,
	[CHANGE_PROD] [bit] NULL,
	[ID_USER] [float] NOT NULL,
 CONSTRAINT [PK_MAINTENANCE_VISIT] PRIMARY KEY CLUSTERED 
(
	[ID_MAIN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MAINTENANCE_VISIT] ADD  DEFAULT ((61)) FOR [ID_USER]
GO


