USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[MAINTENANCE]    Script Date: 05/17/2022 12:04:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MAINTENANCE](
	[ID] [float] NOT NULL,
	[ID_DELIVERY] [float] NOT NULL,
	[CODLOJA] [float] NOT NULL,
	[ID_SALE] [float] NOT NULL,
	[COD_ORIGINAL] [varchar](20) NOT NULL,
	[QUANTIDADE] [float] NOT NULL,
	[STATUS] [varchar](15) NOT NULL,
	[WARRANTY] [bit] NOT NULL,
	[ID_CAT_DEF] [float] NOT NULL,
	[OUTHER_DEF] [varchar](80) NULL,
	[OBS] [varchar](250) NOT NULL,
	[D_ENVIO] [datetime] NOT NULL,
	[D_PREV] [datetime] NOT NULL,
	[D_FINISH] [datetime] NULL,
	[ID_USER] [float] NOT NULL,
 CONSTRAINT [PK_MAINTENANCE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MAINTENANCE] ADD  DEFAULT ((1)) FOR [ID_USER]
GO


