USE [SONOENTREGAS]
GO

/****** Object:  Table [dbo].[MAINTENANCE_ATTEMPT]    Script Date: 03/18/2022 17:50:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MAINTENANCE_ATTEMPT](
	[ID] [float] NOT NULL,
	[ID_MAIN] [float] NOT NULL,
	[CHANGE_PRODUCT] [bit] NOT NULL,
	[D_MOUNTING] [datetime] NOT NULL,
	[D_PROCESS] [datetime] NULL,
	[D_MAINTENANCE] [datetime] NULL,
	[DONE] [bit] NOT NULL,
	[REASON_RETURN] [varchar](250) NULL,
	[ID_DRIVER] [float] NOT NULL,
	[ID_ASSISTANT] [float] NOT NULL,
	[ID_DELIV_MAIN] [float] NULL,
 CONSTRAINT [PK_MAINTENANCE_ATTEMPT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


