CREATE TABLE RETURN_CLIENT_ADDRESS (
  id INT PRIMARY KEY,
  returnIdShop INT NOT NULL,
  shopId INT NOT NULL,
  saleId INT NOT NULL,
  client VARCHAR(60) NOT NULL,
  address VARCHAR(60) NOT NULL,
  houseNumber CHAR(5) NOT NULL,
  district VARCHAR(30) NOT NULL,
  city VARCHAR(25) NOT NULL,
  state VARCHAR(25) NOT NULL,
  phone VARCHAR(11) NOT NULL,
)

CREATE TABLE PRODUCTS_RETURN (
  id INT PRIMARY KEY,
  returnClientAddressId INT NOT NULL FOREIGN KEY REFERENCES RETURN_CLIENT_ADDRESS(id),
  productId INT NOT NULL,
  quantity INT NOT NULL,
  deliveryId INT
)
