-- TABLES PRIMARY
CREATE TABLE BED (
	ID FLOAT NOT NULL,
	DESCRIPTION VARCHAR(80) NOT NULL,
	PRIMARY KEY (ID)
)

CREATE TABLE SIZE (
	ID FLOAT NOT NULL,
	DESCRIPTION VARCHAR(20) NOT NULL,
	WIDTH FLOAT NOT NULL,
	HEIGHT FLOAT NOT NULL,
	LENGTH FLOAT NOT NULL
	PRIMARY KEY (ID)
)

CREATE TABLE CONFIG_BED (
	ID FLOAT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID, DESCRIPTION)
)

CREATE TABLE FEEDSTOCK (
	ID FLOAT NOT NULL,
	COD_SYS VARCHAR(10) NULL,
	DESCRIPTION VARCHAR(80) NOT NULL,
	UND VARCHAR(4) NOT NULL,
	VALUE FLOAT NOT NULL
	PRIMARY KEY (ID)
)

-- TABLE'S RELASIONATION
CREATE TABLE BED_SIZE (
	ID_BED FLOAT NOT NULL,
	ID_SIZE FLOAT NOT NULL,
	COST FLOAT NOT NULL,
	MARGIN FLOAT NULL,
	VALUE FLOAT NULL
	PRIMARY KEY (ID_BED, ID_SIZE)
)

CREATE TABLE BED_CONFIG (
	ID_BED FLOAT NOT NULL,
	ID_CONFIG FLOAT NOT NULL
	PRIMARY KEY (ID_BED, ID_CONFIG)
)

CREATE TABLE BED_FEED (
	ID_BED FLOAT NOT NULL,
	ID_CONFIG FLOAT NOT NULL,
	DESC_CONFIG VARCHAR(20) NOT NULL,
	ID_FEED FLOAT NOT NULL,
	FORMULA VARCHAR(15) NOT NULL
	PRIMARY KEY (ID_BED, DESC_CONFIG, ID_FEED)
)


-- VIEWS
CREATE VIEW VIEW_UND_FEED AS
SELECT UND FROM FEEDSTOCK GROUP BY UND