USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_DELIVERED_BY_DAYS]    Script Date: 12/13/2021 09:19:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[VIEW_DELIVERED_BY_DAYS] AS
select count(A.ID_SALE) as QTD_SALES, A.D_DELIVERED from (
	select ID_SALE, CODLOJA, D_DELIVERED from DELIVERYS_PROD
	where DELIVERED = 0
	and D_DELIVERED is not null
	group by ID_SALE, D_DELIVERED, CODLOJA

) A
GROUP BY A.D_DELIVERED



GO


