USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_DELIVERY_PROD]    Script Date: 08/27/2021 00:58:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_DELIVERY_PROD] AS
SELECT A.ID_DELIVERY, B.*, A.QTD_DELIV,A.D_MOUNTING, A.D_DELIVERING, A.D_DELIVERED, A.DELIVERED
FROM DELIVERYS_PROD A
INNER JOIN SALES_PROD B ON A.ID_SALE = B.ID_SALES AND A.COD_ORIGINAL = B.COD_ORIGINAL AND A.CODLOJA = B.CODLOJA
WHERE A.DELIVERED = 0

GO


