USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_DELIVERY_PROD2]    Script Date: 12/21/2021 11:54:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW [dbo].[VIEW_DELIVERY_PROD2] AS
SELECT A.ID_DELIVERY, B.*, A.QTD_DELIV,A.D_MOUNTING, A.D_DELIVERING, A.D_DELIVERED, A.DELIVERED, A.REASON_RETURN
FROM DELIVERYS_PROD A
INNER JOIN SALES_PROD B ON A.ID_SALE = B.ID_SALES AND A.COD_ORIGINAL = B.COD_ORIGINAL






GO


