USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_D_DELV_ROUTES2]    Script Date: 02/04/2022 18:39:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VIEW_D_DELV_ROUTES2] AS
SELECT ID_DELIVERY, D_DELIVERED
FROM DELIVERYS_PROD 
WHERE D_DELIVERED IS NOT NULL
GROUP BY ID_DELIVERY, D_DELIVERED



GO


