USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_MAINTENANCE]    Script Date: 05/20/2022 07:33:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_MAINTENANCE] AS
SELECT A.*, D.UNITARIO1, C.NOMECLI, D.DESCRICAO PRODUTO, I.DESC_ABREV, I.FULL_NAME SHOP_NAME, B.ID_DELIV_MAIN ID_DELIV_MAINT,
B.ID ID_MAINT_DELIV, C.ENDERECO, C.BAIRRO, C.CIDADE, C.ESTADO, C.CGC_CPF, G.DESCRIPTION AS USERS, H.DESCRIPTION VISITANT,
C.EMISSAO, E.DESCRIPTION CAT_DEFECT, C.FONE, F.DATE_PREV, F.HOURS_PREV, F.DATE DATE_VISIT, F.TO_CD, F.CHANGE_PROD, F.OBS OBS_VISIT
FROM MAINTENANCE A
LEFT JOIN (SELECT * FROM MAINTENANCE_DELIV WHERE DONE = 1) B ON A.ID = B.ID_MAINT
INNER JOIN SALES C ON A.CODLOJA = C.CODLOJA AND A.ID_SALE = C.ID_SALES
INNER JOIN SALES_PROD D ON A.CODLOJA = D.CODLOJA AND A.ID_SALE = D.ID_SALES AND A.COD_ORIGINAL = D.COD_ORIGINAL
LEFT JOIN CAT_DEFECT_MAIN E ON A.ID_CAT_DEF = E.ID
LEFT JOIN MAINTENANCE_VISIT F ON A.ID = F.ID_MAIN
INNER JOIN USERS G ON A.ID_USER = G.ID
LEFT JOIN USERS H ON F.ID_USER = H.ID
INNER JOIN LOJAS I ON A.CODLOJA = I.CODLOJA

GO