CREATE VIEW VIEW_MAINTENANCE_DELIV_PROD AS
SELECT A.*, B.ID_DELIVERY AS ID_DELIV_MAIN, B.DELIVERED FROM MAINTENANCE A
LEFT JOIN DELIVERYS_PROD B 
ON A.ID_DELIVERY = B.ID_DELIVERY AND A.CODLOJA = B.CODLOJA AND A.ID_SALE = B.ID_SALE AND A.COD_ORIGINAL = B.COD_ORIGINAL
