USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_DELIVERY_PROD_MAIN]    Script Date: 03/08/2022 15:44:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VIEW_DELIVERY_PROD_MAIN] AS
SELECT B.STATUS STATUS_MAIN, B.OBS, A.*
FROM VIEW_DELIVERY_PROD2 A
LEFT JOIN MAINTENANCE B 
ON A.ID_DELIVERY = B.ID_DELIVERY AND A.CODLOJA = B.CODLOJA AND A.ID_SALES = B.ID_SALE AND A.COD_ORIGINAL = B.COD_ORIGINAL


GO


