-- Beep
SELECT 1 AS LOJA, DELIV.D_DELIVERED AS DATA, CONVERT(VARCHAR(8), '11:01:02') AS HORA, 'DEVOLUCAO' AS MODULO, CONVERT(VARCHAR(15), RS.id) AS DOCUMENTO,
PROD.CODIGO AS CODPRODUTO, RSP.quantity AS QUANT_ENTRADA, 0 AS QUANT_SAIDA, 'E' AS ENTRADA_SAIDA, CONCAT('Devolução - rota: ', DELIV.ID,'/DAV: ', RS.originalSaleId) AS OBS,
0 AS CODCF, RS.client AS NOMECF, 1 AS EMBALAGEM, 'S' AS CALCULAR, 0 AS VALORUNITARIO, NULL AS LOTE, 'Cliente' AS TIPOCLI_FOR_FUN,
'Padrao' AS USUARIO, 1 AS ITEM, -1 AS MU_ITEM, 1 AS MU_QTE_MENORUN, 'UN' MU_UNIDADE
FROM PRODUTOS PROD
	INNER JOIN  SONOENTREGAS..RETURNS_SALES_PRODUCTS RSP ON PROD.ALTERNATI = RSP.alternativeCode
	INNER JOIN SONOENTREGAS..RETURNS_SALES RS ON RS.id = RSP.returnsSalesId
	INNER JOIN SONOENTREGAS..DELIVERYS DELIV ON DELIV.ID = RS.deliveryId
	INNER JOIN PRODLOJAS_SERIES_MOVIMENTOS PSM ON PSM.inputModuleId = RS.id AND PROD.CODIGO = PSM.productId
WHERE PSM.inputModule = 'saleReturn' AND RS.status = 'Devolvido'

-- Not Beep
SELECT 1 AS LOJA, DELIV.D_DELIVERED AS DATA, CONVERT(VARCHAR(8), '11:01:02') AS HORA, 'DEVOLUCAO' AS MODULO, CONVERT(VARCHAR(15), RS.id) AS DOCUMENTO,
PROD.CODIGO AS CODPRODUTO, RSP.quantity AS QUANT_ENTRADA, 0 AS QUANT_SAIDA, 'E' AS ENTRADA_SAIDA, CONCAT('Devolução - rota: ', DELIV.ID,'/DAV: ', RS.originalSaleId) AS OBS,
0 AS CODCF, RS.client AS NOMECF, 1 AS EMBALAGEM, 'S' AS CALCULAR, 0 AS VALORUNITARIO, NULL AS LOTE, 'Cliente' AS TIPOCLI_FOR_FUN,
'Padrao' AS USUARIO, 1 AS ITEM, -1 AS MU_ITEM, 1 AS MU_QTE_MENORUN, 'UN' MU_UNIDADE
FROM PRODUTOS PROD
	INNER JOIN  SONOENTREGAS..RETURNS_SALES_PRODUCTS RSP ON PROD.ALTERNATI = RSP.alternativeCode
	INNER JOIN SONOENTREGAS..RETURNS_SALES RS ON RS.id = RSP.returnsSalesId
	INNER JOIN SONOENTREGAS..DELIVERYS DELIV ON DELIV.ID = RS.deliveryId
WHERE RS.status = 'Devolvido'
