USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_DELIVERY_PROD_MAINT]    Script Date: 05/18/2022 11:05:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
-- View apenas para verificar se assistência já foi enviada pela loja
CREATE VIEW [dbo].[VIEW_DELIVERY_PROD_MAINT] AS
SELECT B.STATUS STATUS_MAIN, B.D_PREV, B.OBS, A.*
FROM VIEW_DELIVERY_PROD2 A
LEFT JOIN (SELECT * FROM MAINTENANCE WHERE STATUS <> 'Finalizada') B 
ON A.ID_DELIVERY = B.ID_DELIVERY AND A.CODLOJA = B.CODLOJA AND A.ID_SALES = B.ID_SALE AND A.COD_ORIGINAL = B.COD_ORIGINAL
WHERE A.D_DELIVERED IS NOT NULL
GO