USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_D_DELV_ROUTES]    Script Date: 12/21/2021 19:23:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VIEW_D_DELV_ROUTES] AS
SELECT ID_DELIVERY, D_DELIVERED
FROM DELIVERYS_PROD 
WHERE DELIVERED = 0
AND D_DELIVERED IS NOT NULL
GROUP BY ID_DELIVERY, D_DELIVERED


GO


