USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_DELIVERY_PROD2]    Script Date: 04/26/2022 12:36:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_DELIVERY_PROD2] AS
SELECT A.ID_DELIVERY, B.*, A.QTD_DELIV,A.D_MOUNTING, A.D_DELIVERING, A.D_DELIVERED, A.DELIVERED, A.REASON_RETURN,
C.QTD_MOUNTING, C.QTD_DELIVERING, C.QTD_DELIVERED
FROM DELIVERYS_PROD A
INNER JOIN SALES_PROD B 
	ON A.ID_SALE = B.ID_SALES AND A.COD_ORIGINAL = B.COD_ORIGINAL AND A.CODLOJA = B.CODLOJA
LEFT JOIN VIEW_DELIV_PROD_QTD_DELIVERING C 
	ON A.CODLOJA = C.CODLOJA AND A.COD_ORIGINAL = C.COD_ORIGINAL AND A.ID_SALE = C.ID_SALE

GO