USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_QTD_PROD_PENDENTE]    Script Date: 12/13/2021 09:24:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_QTD_PROD_PENDENTE] AS
SELECT COD_ORIGINAL, SUM(QUANTIDADE) QTD
FROM SALES_PROD where STATUS = 'Enviado'
GROUP BY COD_ORIGINAL
GO


