USE [SONOENTREGAS]
GO

/****** Object:  View [dbo].[VIEW_DELIVERY_PROD_MAIN]    Script Date: 04/03/2022 07:21:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



-- View apenas para verificar se assistência já foi enviada pela loja
CREATE VIEW [dbo].[VIEW_DELIVERY_PROD_MAIN] AS
SELECT B.STATUS STATUS_MAIN, B.D_PREV, B.OBS, A.*
FROM VIEW_DELIVERY_PROD2 A
LEFT JOIN MAINTENANCE B 
ON A.ID_DELIVERY = B.ID_DELIVERY AND A.CODLOJA = B.CODLOJA AND A.ID_SALES = B.ID_SALE AND A.COD_ORIGINAL = B.COD_ORIGINAL
WHERE A.D_DELIVERED IS NOT NULL




GO


