module.exports = {
  findSaleProductToForecast({idSale, idShops}){
    return `
    SELECT A.ID_SALE_ID, A.ID_SALES, A.COD_ORIGINAL, A.CODLOJA, A.DESCONTO, A.[STATUS],
    A.QUANTIDADE, ISNULL(B.QTD_MOUNTING, 0) QTD_MOUNTING, A.QUANTIDADE - (ISNULL(B.QTD_MOUNTING, 0)) openQuantity
    FROM SALES_PROD A
    LEFT JOIN (
      SELECT ID_SALE, COD_ORIGINAL, CODLOJA, SUM(QTD_DELIV) QTD_MOUNTING
        FROM DELIVERYS_PROD A
        WHERE DELIVERED = 0
        GROUP BY ID_SALE, COD_ORIGINAL, CODLOJA
    ) B ON A.CODLOJA = B.CODLOJA AND A.ID_SALES = B.ID_SALE AND A.COD_ORIGINAL = B.COD_ORIGINAL
    WHERE A.ID_SALES = ${idSale} AND A.CODLOJA IN (${idShops})`
  },
  findSaleProductMaintenanceToForecast({idSale, idShops}){
    return `
    SELECT A.ID_SALE_ID, A.ID_SALES, A.COD_ORIGINAL, A.CODLOJA, A.DESCONTO, 'Enviado' STATUS,
    B.QUANTIDADE, 0 QTD_MOUNTING, B.QUANTIDADE openQuantity, B.ID ID_MAINTENANCE
    FROM SALES_PROD A
    INNER JOIN MAINTENANCE B ON B.CODLOJA = A.CODLOJA AND B.ID_SALE = A.ID_SALES AND B.COD_ORIGINAL = A.COD_ORIGINAL
    WHERE B.STATUS = 'No CD' AND A.ID_SALES = ${idSale} AND A.CODLOJA IN (${idShops})`
  },
  findSaleMaintenance({idSale}) {
    return `
    SELECT B.ID, B.ID_SALES, B.NOMECLI, B.CODLOJA, B.D_ENTREGA1, B.BAIRRO, 1 isMaintenance, A.STATUS
    FROM MAINTENANCE A
    INNER JOIN SALES B ON A.ID_SALE = B.ID_SALES AND A.CODLOJA = B.CODLOJA
    WHERE A.ID_SALE = ${idSale}
    GROUP BY B.ID, B.ID_SALES, B.NOMECLI, B.CODLOJA, B.D_ENTREGA1, B.BAIRRO, A.STATUS`
  }
}