module.exports = {
  getPendingProductsOutOfStock({date}) {
    return `
    SELECT a.DESCRICAO, A.PEDIDO, A.QTD, A.PED_LOTE_CARGA FROM (
      SELECT A.DESCRICAO, A.PEDIDO, SUM(A.QUANTIDADE) QTD, C.EST_ATUAL, ISNULL(B.FACTORY_DATA, '') PED_LOTE_CARGA
      FROM (
        SELECT
          ID_SALES DAV, DESCRICAO, QUANTIDADE, SP.COD_ORIGINAL, 
          ISNULL((SELECT MIN(B.NUMPEDIDO) FROM PRODUTOS A
          INNER JOIN VIEW_SALDO_PEDIDO_PRODUTO_VALOR B
          ON A.CODIGO = B.CODPRODUTO
          WHERE A.ALTERNATI = SP.COD_ORIGINAL
          AND QTE_CHEGADA <> QTE_PEDIDO
          ), '') PEDIDO
        FROM ${process.env.ENTREGAS_BASE}..SALES_PROD SP
        WHERE ID_SALE_ID IN (
          SELECT ID FROM ${process.env.ENTREGAS_BASE}..SALES
          where D_ENTREGA1 <= '${date}'
          and status = 'Aberta')
        AND SP.STATUS = 'Enviado'
      ) A
      LEFT JOIN PEDFOR B ON A.PEDIDO = B.CODIGOPEDIDO
      LEFT JOIN (
        SELECT A.CODIGO CODPRODUTO, B.EST_ATUAL, A.ALTERNATI
        FROM PRODUTOS A INNER JOIN PRODLOJAS B ON A.CODIGO = B.CODIGO
        WHERE B.CODLOJA = 1
      ) C ON C.ALTERNATI = A.COD_ORIGINAL
      GROUP BY  A.DESCRICAO, A.PEDIDO, B.FACTORY_DATA, C.EST_ATUAL
    ) A WHERE A.EST_ATUAL < A.QTD`
  }
}