const Model = require('../../databases/MSSQL/Model')

class PurchaseNoteProducts extends Model {
  constructor(){
    super('NFITENS', 'NNF, PRODUTO, QUANTIDADE, UNITARIO, VTOTAL, EMBALAGEM, VTOTALIQ, P_IPI, P_ICM, P_DESCONTO, VL_DESCONTO, INDPER, INDVAL, ITEM, DATA, CUSTOVENDA, PRECOVENDA, CODLOJA, MARGEMLUCRO, MARGEMORCIL, ALTMARGPROD, VALOR_IPI, MU_UNIDADE, MU_ITEM, MU_QTE_MENORUN, QUANTIDADE_PROCESSADA, CODIGO_FIGURAPISCOFINS_ALQ, DESC_SUFRAMA, FORMAR_PCO_DESC_SUFRA, CONTROLENF_VENDA,ITEM_NF_VENDA,ORIGEMNF_ITEM ')
  }
}

module.exports = new PurchaseNoteProducts()
