const Model = require('../../databases/MSSQL/Model')

class PurchaseNote extends Model {
  constructor(){
    super('NFISCAL', 'NF, EMISSAO, PROCESS, CODFOR, PEDIDO, VALOR, DESCONT, TOTNF, ICMS, IPI, FRETE, FRETE_P, CODUSUARIO, CFOP, SAIDA, CODTRANSP, CODPLANO, CODLOJA, OBS, EST_DEP_LOJA, COD_NF_SERIES, ENTRADASIMP, DATA_LANCAMENTO, HORA_LANCAMENTO, DATA_CHEGADA, BC_ICMS_SUBS, VALOR_ICMS_SUBS, DESPESAS_ACESSORIOS, DESPESAS_IMPOSTOS, IND_FRT, VEIC_ID, QTD_VOL, PESO_BRT, PESO_LIQ, UF_VEIC_ID, VL_SEG, VOL_ESPE, VOL_MARCA, VOL_NUMEROS, COD_MOD_DOC_FISCAL, SERIE, VL_BC_ICMS, VL_PIS, VL_COFINS, VL_PIS_ST, VL_COFINS_ST, VL_IMPOSTO_IMP, VL_RETPIS, VL_RETCOFINS, COD_PLANO_CONTAS, NUM_DOC, DIVERG_VALOR, PARTICIPA_PRECO, PARTICIPA_ESTOQUE, PARTICIPA_EFD, IND_EMIT, PERC_DESP_PCO_VENDA, PERC_DESP_PCO_PROMO, PERC_DESP_PCO_COMPO, PERC_DESP_PCO_ATACA, PERC_DESP_PCO_ATAC2, PERC_DESP_PCO_ATAC3, PERC_DESP_PCO_ATAC4, PERC_MARG_PCO_VENDA, PERC_MARG_PCO_PROMO, PERC_MARG_PCO_COMPO, PERC_MARG_PCO_ATACA, PERC_MARG_PCO_ATAC2, PERC_MARG_PCO_ATAC3, PERC_MARG_PCO_ATAC4, PARTICIPA_EFD_PISCOFINS, DESC_SUFRAMA, FRETE_ESCRITURAR, TIPO_NF, NF_PRODUTOR, FRETE_NAOESCRITURAR, VFCP, VFCPST, VICMS_DESONERADO, ICMS_DESONERADO_PARTICIPA_NOTA, CODTIPOOPERACAO')
  }
}

module.exports = new PurchaseNote()
