CREATE TABLE BALANCE_BY_BEEP (
	id INT NOT NULL PRIMARY KEY,
	userId INT NOT NULL,
	dtBalance DATETIME NOT NULL,
	description VARCHAR(60) NOT NULL,
	userFinishId INT,
	dtFinish DATETIME
)

CREATE TABLE BALANCE_BY_BEEP_SERIES (
	balanceId INT NOT NULL FOREIGN KEY REFERENCES BALANCE_BY_BEEP(id),
	userId INT NOT NULL,
	dtBeep DATETIME NOT NULL,
	serialNumber INT NOT NULL,
	productIdNotFound INT,
)

CREATE TABLE PRODUCTS_MIRRO (
	balanceId INT NOT NULL FOREIGN KEY REFERENCES BALANCE_BY_BEEP(id),
	idTabSeries INT NOT NULL FOREIGN KEY REFERENCES PRODLOJAS_SERIES_MOVIMENTOS(id),
	productId FLOAT NOT NULL FOREIGN KEY REFERENCES PRODUTOS(CODIGO),
	serialNumber INT NOT NULL,
)
