CREATE TABLE BALANCE_BY_BEEP (
	id INT NOT NULL PRIMARY KEY,
	userId INT NOT NULL,
	dtBalance DATETIME NOT NULL,
	description VARCHAR(60) NOT NULL,
	userFinishId INT,
	dtFinish DATETIME
)

CREATE TABLE BALANCE_BY_BEEP_SERIES (
	idBalance INT NOT NULL FOREIGN KEY REFERENCES BALANCE_BY_BEEP(id),
	serialNumber INT NOT NULL
)
