CREATE TABLE PRODLOJAS_SERIES (
	id INT PRIMARY KEY,
	productId FLOAT NOT NULL FOREIGN KEY REFERENCES PRODUTOS(CODIGO),
	dateEntered DATETIME NOT NULL,
	moduleEntered VARCHAR(12) NOT NULL,
	dateIsOut VARCHAR(12),
	moduleIsOut VARCHAR(12)
)
---------------------------
CREATE TABLE TRANSPRODLOJAI_SERIE (
	transferId FLOAT NOT NULL FOREIGN KEY REFERENCES TRANSPRODLOJA(CODIGO),
	productId FLOAT NOT NULL FOREIGN KEY REFERENCES PRODUTOS(CODIGO),
	serieId INT NOT NULL FOREIGN KEY REFERENCES PRODLOJAS_SERIES(ID),
	CONSTRAINT [PK_CAT_DEFECT_MAIN] PRIMARY KEY CLUSTERED (
		transferId ASC,
		productId ASC,
		serieId ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
