CREATE TABLE PRODLOJAS_SERIES (
	id INT PRIMARY KEY,
	productId FLOAT NOT NULL FOREIGN KEY REFERENCES PRODUTOS(CODIGO),
	serialNumber INT,
	moduleEntered VARCHAR(12) NOT NULL,
	moduleEnteredId INT,
	dateBeepEntered DATETIME NOT NULL,
	moduleIsOut VARCHAR(12),
	moduleIsOutId INT,
	dateBeepIsOut VARCHAR(12)
)
