CREATE TABLE PRODLOJAS_SERIES (
	id INT PRIMARY KEY,
	productId FLOAT NOT NULL FOREIGN KEY REFERENCES PRODUTOS(CODIGO),
	serialNumber INT,
	dateEntered DATETIME NOT NULL,
	moduleEntered VARCHAR(12) NOT NULL,
	dateIsOut VARCHAR(12),
	moduleIsOut VARCHAR(12)
)
