USE SONOENTREGAS
GO

/****** Object:  View [dbo].[VIEW_DELIVERYS]    Script Date: 09/09/2021 15:21:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VIEW_DELIVERYS] AS
SELECT A.ID, A.DESCRIPTION, D.DESCRIPTION CAR, D.PLATE, C.DESCRIPTION ASSISTANT, B.DESCRIPTION DRIVER FROM SONOENTREGAS..DELIVERYS A
INNER JOIN SONOENTREGAS..USERS B ON A.ID_DRIVER = B.ID
INNER JOIN SONOENTREGAS..USERS C ON A.ID_ASSISTANT = C.ID
INNER JOIN SONOENTREGAS..CARS D ON A.ID_CAR = D.ID	


GO