USE [SONO]
GO

/****** Object:  View [dbo].[VIEW_DELIVERYS_PROD]    Script Date: 12/13/2021 11:01:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_DELIVERYS_PROD] AS
SELECT * FROM SONOENTREGAS..VIEW_DELIVERY_PROD
GO


